In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/deceptive-opinion.csv")
df.head()

,deceptive,hotel,polarity,source,text
0,truthful,conrad,positive,TripAdvisor,We stayed for a one night getaway with family ...
1,truthful,hyatt,positive,TripAdvisor,Triple A rate with upgrade to view room was le...
2,truthful,hyatt,positive,TripAdvisor,This comes a little late as I'm finally catchi...
3,truthful,omni,positive,TripAdvisor,The Omni Chicago really delivers on all fronts...
4,truthful,hyatt,positive,TripAdvisor,I asked for a high floor away from the elevato...

In [2]:
df.shape

(1600, 5)

In [3]:
df.columns.tolist()

['deceptive', 'hotel', 'polarity', 'source', 'text']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   deceptive  1600 non-null   str
 1   hotel      1600 non-null   str
 2   polarity   1600 non-null   str
 3   source     1600 non-null   str
 4   text       1600 non-null   str
dtypes: str(5)
memory usage: 62.6 KB

In [5]:
df.isnull().sum()

deceptive    0
hotel        0
polarity     0
source       0
text         0
dtype: int64

In [6]:
df["deceptive"].value_counts()

deceptive
truthful     800
deceptive    800
Name: count, dtype: int64

In [7]:
df["polarity"].value_counts()

polarity
positive    800
negative    800
Name: count, dtype: int64

In [8]:
df["source"].value_counts()

source
MTurk          800
TripAdvisor    400
Web            400
Name: count, dtype: int64

In [9]:
df["hotel"].value_counts()

hotel
conrad              80
hyatt               80
omni                80
fairmont            80
sheraton            80
knickerbocker       80
homewood            80
swissotel           80
ambassador          80
affinia             80
hardrock            80
talbott             80
hilton              80
james               80
monaco              80
sofitel             80
palmer              80
intercontinental    80
allegro             80
amalfi              80
Name: count, dtype: int64

In [10]:
df["text_length"] = df["text"].astype(str).apply(len)
df["text_length"].describe()

count    1600.000000
mean      806.391250
std       467.260647
min       151.000000
25%       487.000000
50%       700.000000
75%       987.500000
max      4159.000000
Name: text_length, dtype: float64

In [11]:
df.duplicated().sum(), df["text"].duplicated().sum()

(np.int64(4), np.int64(4))

In [12]:
df.sample(5)

,deceptive,hotel,polarity,source,text,text_length
454,deceptive,conrad,positive,MTurk,We were amazed by this hotel. The first great ...,532
1238,deceptive,omni,negative,MTurk,I had never been to Chicago and was looking fo...,1601
285,truthful,monaco,positive,TripAdvisor,We had a king deluxe room for 2 nights. We res...,936
1530,deceptive,intercontinental,negative,MTurk,Although the InterContinental Chicago Hotel is...,1590
1269,deceptive,hyatt,negative,MTurk,We decided to spend a little extra to stay at ...,897